import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen">
          <div className="py-4">
            <p>Memcards</p>
          </div>
          <main className="flex-1 px-2 bg-gray-100">{children}</main>
        </div>
      </body>
    </html>
  )
}
