import "../styles/globals.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className="h-full bg-zinc-100 dark:bg-zinc-800 dark:text-zinc-50 text-zinc-800"
    >
      <body className="h-full">{children}</body>
    </html>
  )
}
