import type { Metadata } from "next"
// import { Inter } from 'next/font/google'
import "./globals.css"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <div className="flex flex-col h-full">
          <Navbar />
          <main className="flex-1 px-2 bg-gray-100">{children}</main>
        </div>
      </body>
    </html>
  )
}

const Navbar = () => {
  return (
    <nav className="max-w-2xl px-4 py-4 text-lg">
      <Link href="/">Memcards</Link>
    </nav>
  )
}
