name: "Build App"

runs:
  using: "composite"
  steps:
    - name: Download deps
      uses: bahmutov/npm-install@v1
    - name: Set up Prisma and apply migrations
      shell: bash
      run: npx prisma migrate deploy
    - name: build
      shell: bash
      run: npm run build
